//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/InputSystems/ThirdPersonController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ThirdPersonController: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ThirdPersonController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ThirdPersonController"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""3cad0c7a-c95f-4f13-9588-f5aaf7729ddf"",
            ""actions"": [
                {
                    ""name"": ""PrimaryTouch"",
                    ""type"": ""PassThrough"",
                    ""id"": ""32b20964-3d5b-4e4a-a5f5-1c23c9b1710d"",
                    ""expectedControlType"": ""Touch"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondTouch"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b38f8038-4717-4519-b28a-9e62880e139e"",
                    ""expectedControlType"": ""Touch"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThirdTouch"",
                    ""type"": ""PassThrough"",
                    ""id"": ""609624cb-8b1d-4935-ac6c-0e78a0ce2426"",
                    ""expectedControlType"": ""Touch"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CancelTouch"",
                    ""type"": ""Button"",
                    ""id"": ""263862a3-0b7c-4ec7-a3f6-b24ad4846267"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""c7f1639b-76fd-40d4-bf0a-43105b03010d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AimFire"",
                    ""type"": ""Button"",
                    ""id"": ""04e5db8a-037f-4814-ba20-ba0bbc11b5fe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""12cf45b4-50c7-4dda-ac86-22e50fafd3ae"",
                    ""path"": ""<Touchscreen>/touch0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PointerControl"",
                    ""action"": ""PrimaryTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""54d5e776-5ce4-402a-9b68-8d169f8b177b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d59137d5-7bfb-47a7-bab0-ffe103a08496"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d1df7c3b-f9e9-4202-826b-b85b6c83daef"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6a8e3b5a-3ce7-46f1-ae5c-f2481ebd39b6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4f8c519b-e30d-4347-ae8d-145dc1598120"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""abf0d028-9313-45b7-8972-764027d818d0"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PointerControl"",
                    ""action"": ""AimFire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""376630e4-e0b5-4b43-8b19-2db7af6f83d4"",
                    ""path"": ""<Touchscreen>/touch1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PointerControl"",
                    ""action"": ""SecondTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4113c09d-ba55-49f4-8369-0bd8208af95f"",
                    ""path"": ""<Touchscreen>/touch2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PointerControl"",
                    ""action"": ""ThirdTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""edf6361a-85b6-4a18-a4b6-fd8686c091bb"",
                    ""path"": ""*/{Back}"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": ""PointerControl"",
                    ""action"": ""CancelTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91372eb2-1fcf-4f6c-b340-bfc7460c66a7"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": ""PointerControl"",
                    ""action"": ""CancelTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PointerControl"",
            ""bindingGroup"": ""PointerControl"",
            ""devices"": [
                {
                    ""devicePath"": ""<Pointer>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_PrimaryTouch = m_Player.FindAction("PrimaryTouch", throwIfNotFound: true);
        m_Player_SecondTouch = m_Player.FindAction("SecondTouch", throwIfNotFound: true);
        m_Player_ThirdTouch = m_Player.FindAction("ThirdTouch", throwIfNotFound: true);
        m_Player_CancelTouch = m_Player.FindAction("CancelTouch", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_AimFire = m_Player.FindAction("AimFire", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_PrimaryTouch;
    private readonly InputAction m_Player_SecondTouch;
    private readonly InputAction m_Player_ThirdTouch;
    private readonly InputAction m_Player_CancelTouch;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_AimFire;
    public struct PlayerActions
    {
        private @ThirdPersonController m_Wrapper;
        public PlayerActions(@ThirdPersonController wrapper) { m_Wrapper = wrapper; }
        public InputAction @PrimaryTouch => m_Wrapper.m_Player_PrimaryTouch;
        public InputAction @SecondTouch => m_Wrapper.m_Player_SecondTouch;
        public InputAction @ThirdTouch => m_Wrapper.m_Player_ThirdTouch;
        public InputAction @CancelTouch => m_Wrapper.m_Player_CancelTouch;
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @AimFire => m_Wrapper.m_Player_AimFire;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @PrimaryTouch.started += instance.OnPrimaryTouch;
            @PrimaryTouch.performed += instance.OnPrimaryTouch;
            @PrimaryTouch.canceled += instance.OnPrimaryTouch;
            @SecondTouch.started += instance.OnSecondTouch;
            @SecondTouch.performed += instance.OnSecondTouch;
            @SecondTouch.canceled += instance.OnSecondTouch;
            @ThirdTouch.started += instance.OnThirdTouch;
            @ThirdTouch.performed += instance.OnThirdTouch;
            @ThirdTouch.canceled += instance.OnThirdTouch;
            @CancelTouch.started += instance.OnCancelTouch;
            @CancelTouch.performed += instance.OnCancelTouch;
            @CancelTouch.canceled += instance.OnCancelTouch;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @AimFire.started += instance.OnAimFire;
            @AimFire.performed += instance.OnAimFire;
            @AimFire.canceled += instance.OnAimFire;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @PrimaryTouch.started -= instance.OnPrimaryTouch;
            @PrimaryTouch.performed -= instance.OnPrimaryTouch;
            @PrimaryTouch.canceled -= instance.OnPrimaryTouch;
            @SecondTouch.started -= instance.OnSecondTouch;
            @SecondTouch.performed -= instance.OnSecondTouch;
            @SecondTouch.canceled -= instance.OnSecondTouch;
            @ThirdTouch.started -= instance.OnThirdTouch;
            @ThirdTouch.performed -= instance.OnThirdTouch;
            @ThirdTouch.canceled -= instance.OnThirdTouch;
            @CancelTouch.started -= instance.OnCancelTouch;
            @CancelTouch.performed -= instance.OnCancelTouch;
            @CancelTouch.canceled -= instance.OnCancelTouch;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @AimFire.started -= instance.OnAimFire;
            @AimFire.performed -= instance.OnAimFire;
            @AimFire.canceled -= instance.OnAimFire;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_PointerControlSchemeIndex = -1;
    public InputControlScheme PointerControlScheme
    {
        get
        {
            if (m_PointerControlSchemeIndex == -1) m_PointerControlSchemeIndex = asset.FindControlSchemeIndex("PointerControl");
            return asset.controlSchemes[m_PointerControlSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnPrimaryTouch(InputAction.CallbackContext context);
        void OnSecondTouch(InputAction.CallbackContext context);
        void OnThirdTouch(InputAction.CallbackContext context);
        void OnCancelTouch(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnAimFire(InputAction.CallbackContext context);
    }
}
