// <auto-generated />
using System;
using AccountServer.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231107134515_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AccountServer.DB.AccountDb", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AccountPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerDbPlayerId")
                        .HasColumnType("int");

                    b.HasKey("AccountId");

                    b.HasIndex("AccountName")
                        .IsUnique();

                    b.HasIndex("PlayerDbPlayerId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("AccountServer.DB.InventoryDb", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("InventoryId");

                    b.HasIndex("InventoryId")
                        .IsUnique();

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("AccountServer.DB.ItemDb", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("InventoryDbInventoryId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("InventoryDbInventoryId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Item");
                });

            modelBuilder.Entity("AccountServer.DB.PlayerDb", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("InventoryDbInventoryId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("InventoryDbInventoryId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Player");
                });

            modelBuilder.Entity("AccountServer.DB.AccountDb", b =>
                {
                    b.HasOne("AccountServer.DB.PlayerDb", "PlayerDb")
                        .WithMany()
                        .HasForeignKey("PlayerDbPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerDb");
                });

            modelBuilder.Entity("AccountServer.DB.ItemDb", b =>
                {
                    b.HasOne("AccountServer.DB.InventoryDb", null)
                        .WithMany("Items")
                        .HasForeignKey("InventoryDbInventoryId");
                });

            modelBuilder.Entity("AccountServer.DB.PlayerDb", b =>
                {
                    b.HasOne("AccountServer.DB.InventoryDb", "InventoryDb")
                        .WithMany()
                        .HasForeignKey("InventoryDbInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryDb");
                });

            modelBuilder.Entity("AccountServer.DB.InventoryDb", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
