// <auto-generated />
using System;
using AccountServer.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231117065011_init3")]
    partial class init3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AccountServer.DB.ItemDb", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.HasIndex("PlayerId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("AccountServer.DB.PlayerDb", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LoginType")
                        .HasColumnType("int");

                    b.Property<string>("OauthToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PlayerStatId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.HasIndex("PlayerStatId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("AccountServer.DB.PlayerStatDb", b =>
                {
                    b.Property<int>("PlayerStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Atk")
                        .HasColumnType("int");

                    b.Property<float>("AtkSpeed")
                        .HasColumnType("float");

                    b.Property<float>("CritDamage")
                        .HasColumnType("float");

                    b.Property<int>("CritRate")
                        .HasColumnType("int");

                    b.Property<float>("DodgeTime")
                        .HasColumnType("float");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxHp")
                        .HasColumnType("int");

                    b.Property<float>("MoveSpeed")
                        .HasColumnType("float");

                    b.Property<float>("RunMultiplier")
                        .HasColumnType("float");

                    b.HasKey("PlayerStatId");

                    b.HasIndex("PlayerStatId")
                        .IsUnique();

                    b.ToTable("Player_Stat");
                });

            modelBuilder.Entity("AccountServer.DB.ItemDb", b =>
                {
                    b.HasOne("AccountServer.DB.PlayerDb", "Player")
                        .WithMany("Items")
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AccountServer.DB.PlayerDb", b =>
                {
                    b.HasOne("AccountServer.DB.PlayerStatDb", "PlayerStat")
                        .WithMany()
                        .HasForeignKey("PlayerStatId");

                    b.Navigation("PlayerStat");
                });

            modelBuilder.Entity("AccountServer.DB.PlayerDb", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
