// <auto-generated />
using System;
using AccountServer.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231118034046_itemDb")]
    partial class itemDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AccountServer.Model.CurrencyDb", b =>
                {
                    b.Property<int>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Diamond")
                        .HasColumnType("int");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId1")
                        .HasColumnType("int");

                    b.HasKey("CurrencyId");

                    b.HasIndex("CurrencyId")
                        .IsUnique();

                    b.HasIndex("PlayerId1");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("AccountServer.Model.GuestDb", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GuestUid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerId1")
                        .HasColumnType("int");

                    b.HasKey("GuestId");

                    b.HasIndex("GuestId")
                        .IsUnique();

                    b.HasIndex("PlayerId1");

                    b.ToTable("Guest");
                });

            modelBuilder.Entity("AccountServer.Model.InventoryDb", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PlayerId1")
                        .HasColumnType("int");

                    b.HasKey("InventoryId");

                    b.HasIndex("InventoryId")
                        .IsUnique();

                    b.HasIndex("PlayerId1");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("AccountServer.Model.Item.MaterialItemDb", b =>
                {
                    b.Property<int>("MaterialItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("InventoryId1")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("MaterialItemId");

                    b.HasIndex("InventoryId1");

                    b.HasIndex("MaterialItemId")
                        .IsUnique();

                    b.ToTable("MaterialItem");
                });

            modelBuilder.Entity("AccountServer.Model.Item.PotionItemDb", b =>
                {
                    b.Property<int>("PotionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("InventoryId1")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("PotionItemId");

                    b.HasIndex("InventoryId1");

                    b.HasIndex("PotionItemId")
                        .IsUnique();

                    b.ToTable("PotionItem");
                });

            modelBuilder.Entity("AccountServer.Model.Item.RuneItemDb", b =>
                {
                    b.Property<int>("RuneItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Equipped")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("InventoryId1")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("RuneItemId");

                    b.HasIndex("InventoryId1");

                    b.ToTable("RuneItem");
                });

            modelBuilder.Entity("AccountServer.Model.Item.WeaponItemDb", b =>
                {
                    b.Property<int>("WeaponItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Equipped")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("InventoryId1")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("WeaponItemId");

                    b.HasIndex("InventoryId1");

                    b.ToTable("WeaponItem");
                });

            modelBuilder.Entity("AccountServer.Model.OauthDb", b =>
                {
                    b.Property<int>("OauthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OauthToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerId1")
                        .HasColumnType("int");

                    b.Property<int>("oatuhType")
                        .HasColumnType("int");

                    b.HasKey("OauthId");

                    b.HasIndex("OauthId")
                        .IsUnique();

                    b.HasIndex("PlayerId1");

                    b.ToTable("Oauth");
                });

            modelBuilder.Entity("AccountServer.Model.PlayerDb", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PlayerId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Player");
                });

            modelBuilder.Entity("AccountServer.Model.PlayerStatDb", b =>
                {
                    b.Property<int>("PlayerStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Atk")
                        .HasColumnType("int");

                    b.Property<float>("AtkSpeed")
                        .HasColumnType("float");

                    b.Property<float>("CritDamage")
                        .HasColumnType("float");

                    b.Property<int>("CritRate")
                        .HasColumnType("int");

                    b.Property<float>("DodgeTime")
                        .HasColumnType("float");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxHp")
                        .HasColumnType("int");

                    b.Property<float>("MoveSpeed")
                        .HasColumnType("float");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<float>("RunMultiplier")
                        .HasColumnType("float");

                    b.HasKey("PlayerStatId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerStatId")
                        .IsUnique();

                    b.ToTable("Player_Stat");
                });

            modelBuilder.Entity("AccountServer.Model.CurrencyDb", b =>
                {
                    b.HasOne("AccountServer.Model.PlayerDb", "PlayerId")
                        .WithMany()
                        .HasForeignKey("PlayerId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerId");
                });

            modelBuilder.Entity("AccountServer.Model.GuestDb", b =>
                {
                    b.HasOne("AccountServer.Model.PlayerDb", "PlayerId")
                        .WithMany()
                        .HasForeignKey("PlayerId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerId");
                });

            modelBuilder.Entity("AccountServer.Model.InventoryDb", b =>
                {
                    b.HasOne("AccountServer.Model.PlayerDb", "PlayerId")
                        .WithMany()
                        .HasForeignKey("PlayerId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerId");
                });

            modelBuilder.Entity("AccountServer.Model.Item.MaterialItemDb", b =>
                {
                    b.HasOne("AccountServer.Model.InventoryDb", "InventoryId")
                        .WithMany("MaterialItems")
                        .HasForeignKey("InventoryId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryId");
                });

            modelBuilder.Entity("AccountServer.Model.Item.PotionItemDb", b =>
                {
                    b.HasOne("AccountServer.Model.InventoryDb", "InventoryId")
                        .WithMany("PotionItems")
                        .HasForeignKey("InventoryId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryId");
                });

            modelBuilder.Entity("AccountServer.Model.Item.RuneItemDb", b =>
                {
                    b.HasOne("AccountServer.Model.InventoryDb", "InventoryId")
                        .WithMany("RuneItems")
                        .HasForeignKey("InventoryId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryId");
                });

            modelBuilder.Entity("AccountServer.Model.Item.WeaponItemDb", b =>
                {
                    b.HasOne("AccountServer.Model.InventoryDb", "InventoryId")
                        .WithMany("WeaponItems")
                        .HasForeignKey("InventoryId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryId");
                });

            modelBuilder.Entity("AccountServer.Model.OauthDb", b =>
                {
                    b.HasOne("AccountServer.Model.PlayerDb", "PlayerId")
                        .WithMany()
                        .HasForeignKey("PlayerId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerId");
                });

            modelBuilder.Entity("AccountServer.Model.PlayerStatDb", b =>
                {
                    b.HasOne("AccountServer.Model.PlayerDb", "playerId")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("playerId");
                });

            modelBuilder.Entity("AccountServer.Model.InventoryDb", b =>
                {
                    b.Navigation("MaterialItems");

                    b.Navigation("PotionItems");

                    b.Navigation("RuneItems");

                    b.Navigation("WeaponItems");
                });
#pragma warning restore 612, 618
        }
    }
}
